### ISSUE TITLE
Feature: Copy Button Component

### ISSUE THREAD

**Issue by Zyruks** [serudda/side-ui#7]
## Description:
Serudda has requested the addition of a new Copy Button component for the Twon project. It is suggested to include this component in the side-ui component library for better reusability across the project.

[Twon Issue](https://github.com/serudda/twon/issues/31)

## Requirements:

- The Copy Button component should provide a user-friendly way to copy text or content to the clipboard.
- It should be flexible enough to be used with various types of target elements, such as headings, divs, buttons, and others.
- The component should have customizable options for size, color, variant, and icon style.
- It should display a tooltip indicating whether the content has been copied successfully.
- The Copy Button should be visually consistent with the existing components in the side-ui library.

**Comment by serudda** [comment]
DONE
